export const products = [
  {
    id: 1,
    brand: "Alpha Pharma",
    product: "BOLDEBOLIN (BOLDY)",
    composition: "",
    quantity: "10ML",
    potency: "250MG",
    price: 1450,
    category: "",
  },
  {
    id: 2,
    brand: "Alpha Pharma",
    product: "NANDROBOLIN (DECA)",
    composition: "",
    quantity: "10ML",
    potency: "250MG",
    price: 1450,
    category: "",
  },
  {
    id: 3,
    brand: "Alpha Pharma",
    product: "TESTOBOLIN (TEST ENAN)",
    composition: "",
    quantity: "10ML",
    potency: "250MG",
    price: 1300,
    category: "",
  },
  {
    id: 4,
    brand: "Alpha Pharma",
    product: "TEST CYPO",
    composition: "",
    quantity: "10ML",
    potency: "250MG",
    price: 1300,
    category: "",
  },
  {
    id: 5,
    brand: "Alpha Pharma",
    product: "TESTO RAPID (TEST PROP)",
    composition: "",
    quantity: "10ML",
    potency: "100MG",
    price: 1075,
    category: "",
  },
  {
    id: 6,
    brand: "Alpha Pharma",
    product: "INDUJECT (SUSTA)",
    composition: "",
    quantity: "10ML",
    potency: "250MG",
    price: 1300,
    category: "",
  },
  {
    id: 7,
    brand: "Alpha Pharma",
    product: "TRENARAPID (TREN ACETATE)",
    composition: "",
    quantity: "10ML",
    potency: "100MG",
    price: 2650,
    category: "",
  },
  {
    id: 8,
    brand: "Alpha Pharma",
    product: "PARABOLIN (TREN HEXA)",
    composition: "",
    quantity: "10ML",
    potency: "75MG",
    price: 3000,
    category: "",
  },
  {
    id: 9,
    brand: "Alpha Pharma",
    product: "MASTEBOLIN (MASTERON)",
    composition: "",
    quantity: "10ML",
    potency: "100MG",
    price: 1850,
    category: "",
  },
  {
    id: 10,
    brand: "Alpha Pharma",
    product: "ALPHABOLIN (PRIMO)",
    composition: "",
    quantity: "10ML",
    potency: "100MG",
    price: 2925,
    category: "",
  },
  {
    id: 11,
    brand: "Alpha Pharma",
    product: "NANDRORAPID (NPP)",
    composition: "",
    quantity: "10ML",
    potency: "100MG",
    price: 1650,
    category: "",
  },
  {
    id: 12,
    brand: "Alpha Pharma",
    product: "REXOGIN (WINNY)",
    composition: "",
    quantity: "10ML",
    potency: "50MG",
    price: 1450,
    category: "",
  },
  {
    id: 13,
    brand: "Alpha Pharma",
    product: "TESTOBASE (TEST SUSPENSION)",
    composition: "",
    quantity: "10ML",
    potency: "100MG",
    price: 1650,
    category: "",
  },
  {
    id: 14,
    brand: "Alpha Pharma",
    product: "TREN ENAN",
    composition: "",
    quantity: "10ML",
    potency: "250MG",
    price: 4250,
    category: "",
  },
  {
    id: 15,
    brand: "Alpha Pharma",
    product: "TESTO EXTEND",
    composition: "",
    quantity: "4ML",
    potency: "250MG",
    price: 750,
    category: "",
  },
  {
    id: 16,
    brand: "Alpha Pharma",
    product: "ASTRALEAN (CLEN)",
    composition: "",
    quantity: "100TABS",
    potency: "40MCG",
    price: 800,
    category: "",
  },
  {
    id: 17,
    brand: "Alpha Pharma",
    product: "ASTRALEAN (CLEN)",
    composition: "",
    quantity: "50TABS",
    potency: "40MCG",
    price: 425,
    category: "",
  },
  {
    id: 18,
    brand: "Alpha Pharma",
    product: "THYRO3 (T3)",
    composition: "",
    quantity: "30TABS",
    potency: "25MCG",
    price: 310,
    category: "",
  },
  {
    id: 19,
    brand: "Alpha Pharma",
    product: "OXANABOL (OXY)",
    composition: "",
    quantity: "50TABS",
    potency: "10MG",
    price: 1925,
    category: "",
  },
  {
    id: 20,
    brand: "Alpha Pharma",
    product: "OXYDROLONE (ANAVAR)",
    composition: "",
    quantity: "50TABS",
    potency: "50MG",
    price: 1925,
    category: "",
  },
  {
    id: 21,
    brand: "Alpha Pharma",
    product: "ALPHABOL (DANA)",
    composition: "",
    quantity: "100TABS",
    potency: "10MG",
    price: 1025,
    category: "",
  },
  {
    id: 22,
    brand: "Alpha Pharma",
    product: "REXOBOL (STANA TAB)",
    composition: "",
    quantity: "100TABS",
    potency: "10MG",
    price: 1025,
    category: "",
  },
  {
    id: 23,
    brand: "Alpha Pharma",
    product: "REXOBOL (STANA TAB)",
    composition: "",
    quantity: "50TABS",
    potency: "50MG",
    price: 2200,
    category: "",
  },
  {
    id: 24,
    brand: "Alpha Pharma",
    product: "PROVIBOL (PROVIRON)",
    composition: "",
    quantity: "50TABS",
    potency: "25MG",
    price: 1050,
    category: "",
  },
  {
    id: 25,
    brand: "Alpha Pharma",
    product: "ANAZOLE (ANASTROZOLE)",
    composition: "",
    quantity: "30TABS",
    potency: "1MG",
    price: 1100,
    category: "",
  },
  {
    id: 26,
    brand: "Alpha Pharma",
    product: "TESTOTABS",
    composition: "",
    quantity: "50TABS",
    potency: "40MG",
    price: 700,
    category: "",
  },
  {
    id: 27,
    brand: "sp",
    product: "HGH191AA",
    composition: "HUMAN GROWTH HORMONE 191AA",
    quantity: "",
    potency: "10IU X 1VIAL",
    price: 900,
    category: "",
  },
  {
    id: 28,
    brand: "sp",
    product: "HGH-FRAG",
    composition: "HGH FRAGMENT 176-191",
    quantity: "",
    potency: "6MG X 1VIAL",
    price: 1000,
    category: "",
  },
  {
    id: 29,
    brand: "sp",
    product: "GHRP-6",
    composition: "GROWTH HORMONE RELEASING PEPTIDE-6",
    quantity: "",
    potency: "5MG X 1VIAL",
    price: 800,
    category: "",
  },
  {
    id: 30,
    brand: "sp",
    product: "IGF-1LR3",
    composition: "INSULIN-LIKE GROWTH FACTOR 1 LONG R3",
    quantity: "",
    potency: "125MCG X 1VIAL",
    price: 900,
    category: "",
  },
  {
    id: 31,
    brand: "sp",
    product: "IPAMORELIN",
    composition: "GROWTH HORMONE RELEASING PENTA PEPTIDE",
    quantity: "",
    potency: "5MG X 1VIAL",
    price: 1100,
    category: "",
  },
  {
    id: 32,
    brand: "sp",
    product: "GONADORELIN",
    composition: "GONADORELIN (WASHOUT CYCLE)",
    quantity: "",
    potency: "10MG X 1VIAL",
    price: 1200,
    category: "",
  },
  {
    id: 33,
    brand: "sp",
    product: "MOD GRF (1-29)",
    composition: "CJC-1295 NON DAC",
    quantity: "",
    potency: "2MG X 1VIAL",
    price: 800,
    category: "",
  },
  {
    id: 34,
    brand: "sp",
    product: "CJC-1295 DAC",
    composition: "CJC-1295 WITH DRUG AFFINITY COMPLEX",
    quantity: "",
    potency: "2MG X 1VIAL",
    price: 900,
    category: "",
  },
  {
    id: 35,
    brand: "sp",
    product: "FST-344",
    composition: "FOLLSTATIN-344",
    quantity: "",
    potency: "1MG X 1VIAL",
    price: 3500,
    category: "",
  },
  {
    id: 36,
    brand: "sp",
    product: "PT-141",
    composition: "BREMELANOTIDE",
    quantity: "",
    potency: "10MG X 1VIAL",
    price: 2500,
    category: "",
  },
  {
    id: 37,
    brand: "sp",
    product: "BPC-157",
    composition: "BODY PROTECTION COMPOUND",
    quantity: "",
    potency: "5MG X 1VIAL",
    price: 1500,
    category: "",
  },
  {
    id: 38,
    brand: "sp",
    product: "TB-500",
    composition: "THYMOSIN BETA-4",
    quantity: "",
    potency: "10MG X 1VIAL",
    price: 2400,
    category: "",
  },
  {
    id: 39,
    brand: "sp",
    product: "RECOVERY BLEND",
    composition: "BPC-157 + TB-500",
    quantity: "",
    potency: "10MG X 1VIAL",
    price: 3200,
    category: "",
  },
  {
    id: 40,
    brand: "sp",
    product: "ADIPOTIDE (FTPP)",
    composition: "FAT TARGETED PROAPOPTIC PEPTIDE",
    quantity: "",
    potency: "10MG X 1VIAL",
    price: 2500,
    category: "",
  },
  {
    id: 41,
    brand: "sp",
    product: "GAINING BLEND",
    composition: "GHRP-6 + MOD GRF + HEXARELIN",
    quantity: "",
    potency: "15MG X 1VIAL",
    price: 2000,
    category: "",
  },
  {
    id: 42,
    brand: "sp",
    product: "LEAN GAIN BLEND",
    composition: "GHRP-2 + CJC-1295 + IPAMORELIN",
    quantity: "",
    potency: "9MG X 1VIAL",
    price: 2400,
    category: "",
  },
  {
    id: 43,
    brand: "sp",
    product: "RIPPING BLEND",
    composition: "TESAMORELIN CJC-1295 + IPAMORELIN",
    quantity: "",
    potency: "12MG X 1VIAL",
    price: 2000,
    category: "",
  },
  {
    id: 44,
    brand: "sp",
    product: "FAT OFF BLEND",
    composition: "HGH FRAG + CJC-1295 + IPAMORELIN",
    quantity: "",
    potency: "12MG X 1VIAL",
    price: 3000,
    category: "",
  },
  {
    id: 45,
    brand: "sp",
    product: "PGCL",
    composition: "CLOPROSTENOL SODIUM",
    quantity: "",
    potency: "2MG X 1VIAL",
    price: 550,
    category: "",
  },
  {
    id: 46,
    brand: "sp",
    product: "AOD",
    composition: "ANTI OBESITY DRUG",
    quantity: "",
    potency: "2MG X 1VIAL",
    price: 1300,
    category: "",
  },
  {
    id: 47,
    brand: "sp",
    product: "SEMAGLUTIDE",
    composition: "SEMAGLUTIDE (GLP-1 ANALOGUE)",
    quantity: "",
    potency: "2MG X 1VIAL",
    price: 3500,
    category: "",
  },
  {
    id: 48,
    brand: "sp",
    product: "GROWTH FACTOR MIX",
    composition: "IGF-1LR3 + MGF",
    quantity: "",
    potency: "2125MCG X 1VIAL",
    price: 1500,
    category: "",
  },
  {
    id: 49,
    brand: "sp",
    product: "IGF-1 DES",
    composition: "RECOMBINANT IGF-1DES",
    quantity: "",
    potency: "1MG X 1VIAL",
    price: 1000,
    category: "",
  },
  {
    id: 50,
    brand: "sp",
    product: "BACTERIOSTATIC WATER",
    composition: "BACTERIOSTATIC WATER",
    quantity: "",
    potency: "10ML X 1VIAL",
    price: 400,
    category: "",
  },
  {
    id: 51,
    brand: "infinity pharma",
    product: "DECA 300",
    composition: "",
    quantity: "",
    potency: "",
    price: 1700,
    category: "INJECTABLES",
  },
  {
    id: 52,
    brand: "infinity pharma",
    product: "BOLDY 300",
    composition: "",
    quantity: "",
    potency: "",
    price: 1750,
    category: "INJECTABLES",
  },
  {
    id: 53,
    brand: "infinity pharma",
    product: "TEST ENAN 300",
    composition: "",
    quantity: "",
    potency: "",
    price: 1450,
    category: "INJECTABLES",
  },
  {
    id: 54,
    brand: "infinity pharma",
    product: "TEST CYPO 300",
    composition: "",
    quantity: "",
    potency: "",
    price: 1450,
    category: "INJECTABLES",
  },
  {
    id: 55,
    brand: "infinity pharma",
    product: "TEST PROP 125",
    composition: "",
    quantity: "",
    potency: "",
    price: 950,
    category: "INJECTABLES",
  },
  {
    id: 56,
    brand: "infinity pharma",
    product: "SUSTA 400",
    composition: "",
    quantity: "",
    potency: "",
    price: 1700,
    category: "INJECTABLES",
  },
  {
    id: 57,
    brand: "infinity pharma",
    product: "TREN ENAN 250",
    composition: "",
    quantity: "",
    potency: "",
    price: 2900,
    category: "INJECTABLES",
  },
  {
    id: 58,
    brand: "infinity pharma",
    product: "WINSTROL 100",
    composition: "",
    quantity: "",
    potency: "",
    price: 1650,
    category: "INJECTABLES",
  },
  {
    id: 59,
    brand: "infinity pharma",
    product: "TREN ACE 100",
    composition: "",
    quantity: "",
    potency: "",
    price: 2550,
    category: "INJECTABLES",
  },
  {
    id: 60,
    brand: "infinity pharma",
    product: "MASTERON 100",
    composition: "",
    quantity: "",
    potency: "",
    price: 2450,
    category: "INJECTABLES",
  },
  {
    id: 61,
    brand: "infinity pharma",
    product: "PRIMO",
    composition: "",
    quantity: "",
    potency: "",
    price: 3050,
    category: "INJECTABLES",
  },
  {
    id: 62,
    brand: "infinity pharma",
    product: "TREN HEXA",
    composition: "",
    quantity: "",
    potency: "",
    price: 3050,
    category: "INJECTABLES",
  },
  {
    id: 63,
    brand: "infinity pharma",
    product: "POWER PRO MAX",
    composition: "",
    quantity: "",
    potency: "",
    price: 4000,
    category: "BLENDS",
  },
  {
    id: 64,
    brand: "infinity pharma",
    product: "CUT PRO MAX",
    composition: "",
    quantity: "",
    potency: "",
    price: 3900,
    category: "BLENDS",
  },
  {
    id: 65,
    brand: "infinity pharma",
    product: "BULK PRO MAX",
    composition: "",
    quantity: "",
    potency: "",
    price: 4000,
    category: "BLENDS",
  },
  {
    id: 66,
    brand: "infinity pharma",
    product: "ANAVAR 10 MG",
    composition: "",
    quantity: "",
    potency: "",
    price: 2250,
    category: "ORALS",
  },
  {
    id: 67,
    brand: "infinity pharma",
    product: "STANA TAB 10 MG",
    composition: "",
    quantity: "",
    potency: "",
    price: 1100,
    category: "ORALS",
  },
  {
    id: 68,
    brand: "infinity pharma",
    product: "DANABOL 20 MG",
    composition: "",
    quantity: "",
    potency: "",
    price: 1100,
    category: "ORALS",
  },
  {
    id: 69,
    brand: "infinity pharma",
    product: "CLEN 40 MCG",
    composition: "",
    quantity: "",
    potency: "",
    price: 900,
    category: "ORALS",
  },
  {
    id: 70,
    brand: "infinity pharma",
    product: "T3 25 MCG",
    composition: "",
    quantity: "",
    potency: "",
    price: 900,
    category: "ORALS",
  },
  {
    id: 71,
    brand: "infinity pharma",
    product: "ANADROL (OXY) 50 MG - 50 TABS",
    composition: "",
    quantity: "",
    potency: "",
    price: 1500,
    category: "ORALS",
  },
  {
    id: 72,
    brand: "infinity pharma",
    product: "TURINABOL 10 MG - 100 TABS",
    composition: "",
    quantity: "",
    potency: "",
    price: 2200,
    category: "ORALS",
  },
  {
    id: 73,
    brand: "infinity pharma",
    product: "PROVIRON 25 MG - 50 TABS",
    composition: "",
    quantity: "",
    potency: "",
    price: 2100,
    category: "ORALS",
  },
  {
    id: 74,
    brand: "infinity pharma",
    product: "SUPERDROL 15 MG - 60 TABS",
    composition: "",
    quantity: "",
    potency: "",
    price: 2000,
    category: "ORALS",
  },
  {
    id: 75,
    brand: "infinity pharma",
    product: "HGH PRO MAX (50 CAPS)",
    composition: "",
    quantity: "",
    potency: "",
    price: 3000,
    category: "SERMS",
  },
  {
    id: 76,
    brand: "infinity pharma",
    product: "POST GEAR PRO (78 CAPS)",
    composition: "",
    quantity: "",
    potency: "",
    price: 2000,
    category: "SERMS",
  },
  {
    id: 77,
    brand: "infinity pharma",
    product: "HGH 140 IU",
    composition: "",
    quantity: "",
    potency: "",
    price: 13500,
    category: "PEPTIDE",
  },
  {
    id: 78,
    brand: "German Remedies",
    product: "DECA 250",
    composition: "",
    quantity: "",
    potency: "",
    price: 1250,
    category: "Injectables",
  },
  {
    id: 79,
    brand: "German Remedies",
    product: "NPP",
    composition: "",
    quantity: "",
    potency: "",
    price: 1375,
    category: "Injectables",
  },
  {
    id: 80,
    brand: "German Remedies",
    product: "BOLDY 250",
    composition: "",
    quantity: "",
    potency: "",
    price: 1375,
    category: "Injectables",
  },
  {
    id: 81,
    brand: "German Remedies",
    product: "BOLDY 400",
    composition: "",
    quantity: "",
    potency: "",
    price: 1595,
    category: "Injectables",
  },
  {
    id: 82,
    brand: "German Remedies",
    product: "TEST E",
    composition: "",
    quantity: "",
    potency: "",
    price: 1155,
    category: "Injectables",
  },
  {
    id: 83,
    brand: "German Remedies",
    product: "TEST C",
    composition: "",
    quantity: "",
    potency: "",
    price: 1155,
    category: "Injectables",
  },
  {
    id: 84,
    brand: "German Remedies",
    product: "SUSTANON 250",
    composition: "",
    quantity: "",
    potency: "",
    price: 1190,
    category: "Injectables",
  },
  {
    id: 85,
    brand: "German Remedies",
    product: "TEST P",
    composition: "",
    quantity: "",
    potency: "",
    price: 880,
    category: "Injectables",
  },
  {
    id: 86,
    brand: "German Remedies",
    product: "NAND BLEND (DECA) 300",
    composition: "",
    quantity: "",
    potency: "",
    price: 1595,
    category: "Injectables",
  },
  {
    id: 87,
    brand: "German Remedies",
    product: "TREN ACE 100",
    composition: "",
    quantity: "",
    potency: "",
    price: 1850,
    category: "Injectables",
  },
  {
    id: 88,
    brand: "German Remedies",
    product: "TREN HEXA 76.5",
    composition: "",
    quantity: "",
    potency: "",
    price: 2035,
    category: "Injectables",
  },
  {
    id: 89,
    brand: "German Remedies",
    product: "TRI TREN (TRENMIX)",
    composition: "",
    quantity: "",
    potency: "",
    price: 2475,
    category: "Injectables",
  },
  {
    id: 90,
    brand: "German Remedies",
    product: "TREN DEPOT (E)",
    composition: "",
    quantity: "",
    potency: "",
    price: 2475,
    category: "Injectables",
  },
  {
    id: 91,
    brand: "German Remedies",
    product: "TREN AQ (SUSPENSION)",
    composition: "",
    quantity: "",
    potency: "",
    price: 1250,
    category: "Injectables",
  },
  {
    id: 92,
    brand: "German Remedies",
    product: "TEST BASE (SUSPENSION)",
    composition: "",
    quantity: "",
    potency: "",
    price: 1000,
    category: "Injectables",
  },
  {
    id: 93,
    brand: "German Remedies",
    product: "STANA OIL BASED",
    composition: "",
    quantity: "",
    potency: "",
    price: 1155,
    category: "Injectables",
  },
  {
    id: 94,
    brand: "German Remedies",
    product: "STANA WATER BASED 20ML",
    composition: "",
    quantity: "",
    potency: "",
    price: 1300,
    category: "Injectables",
  },
  {
    id: 95,
    brand: "German Remedies",
    product: "PRIMO",
    composition: "",
    quantity: "",
    potency: "",
    price: 2475,
    category: "Injectables",
  },
  {
    id: 96,
    brand: "German Remedies",
    product: "MASTERON",
    composition: "",
    quantity: "",
    potency: "",
    price: 1750,
    category: "Injectables",
  },
  {
    id: 97,
    brand: "German Remedies",
    product: "HELIOS",
    composition: "",
    quantity: "",
    potency: "",
    price: 1600,
    category: "Injectables",
  },
  {
    id: 98,
    brand: "German Remedies",
    product: "VAR SHOT (ANAVAR INJECT)",
    composition: "",
    quantity: "",
    potency: "",
    price: 1800,
    category: "Injectables",
  },
  {
    id: 99,
    brand: "German Remedies",
    product: "GR LEAN GAIN (BLEND)",
    composition: "",
    quantity: "",
    potency: "",
    price: 3080,
    category: "Blends",
  },
  {
    id: 100,
    brand: "German Remedies",
    product: "GR LEAN BULK (BLEND)",
    composition: "",
    quantity: "",
    potency: "",
    price: 2365,
    category: "Blends",
  },
  {
    id: 101,
    brand: "German Remedies",
    product: "GR MEGA LEAN (BLEND)",
    composition: "",
    quantity: "",
    potency: "",
    price: 2420,
    category: "Blends",
  },
  {
    id: 102,
    brand: "German Remedies",
    product: "GR ULTRA LEAN (BLEND)",
    composition: "",
    quantity: "",
    potency: "",
    price: 2700,
    category: "Blends",
  },
  {
    id: 103,
    brand: "German Remedies",
    product: "GR VAR 10-100TABS (ANAVAR)",
    composition: "",
    quantity: "",
    potency: "",
    price: 2145,
    category: "Tablets",
  },
  {
    id: 104,
    brand: "German Remedies",
    product: "GR ZOL 10-100TABS (STANA)",
    composition: "",
    quantity: "",
    potency: "",
    price: 880,
    category: "Tablets",
  },
  {
    id: 105,
    brand: "German Remedies",
    product: "GR OXY 50-50TABS",
    composition: "",
    quantity: "",
    potency: "",
    price: 1190,
    category: "Tablets",
  },
  {
    id: 106,
    brand: "German Remedies",
    product: "GR DBOL 10-100TABS",
    composition: "",
    quantity: "",
    potency: "",
    price: 440,
    category: "Tablets",
  },
  {
    id: 107,
    brand: "German Remedies",
    product: "GR CLEN 40-100TABS",
    composition: "",
    quantity: "",
    potency: "",
    price: 625,
    category: "Tablets",
  },
  {
    id: 108,
    brand: "German Remedies",
    product: "GR T3 25-100TABS",
    composition: "",
    quantity: "",
    potency: "",
    price: 575,
    category: "Tablets",
  },
  {
    id: 109,
    brand: "German Remedies",
    product: "GR TBOL 10-100TABS",
    composition: "",
    quantity: "",
    potency: "",
    price: 1650,
    category: "Tablets",
  },
  {
    id: 110,
    brand: "German Remedies",
    product: "GR M-DROL 30-30TABS",
    composition: "",
    quantity: "",
    potency: "",
    price: 1485,
    category: "Tablets",
  },
  {
    id: 111,
    brand: "German Remedies",
    product: "GR PROVI 25-50TABS",
    composition: "",
    quantity: "",
    potency: "",
    price: 1550,
    category: "Tablets",
  },
  {
    id: 112,
    brand: "German Remedies",
    product: "GR CLOMID-50 50TABS",
    composition: "",
    quantity: "",
    potency: "",
    price: 715,
    category: "Tablets",
  },
  {
    id: 113,
    brand: "German Remedies",
    product: "GR LETRO-30TABS",
    composition: "",
    quantity: "",
    potency: "",
    price: 660,
    category: "Tablets",
  },
  {
    id: 114,
    brand: "German Remedies",
    product: "GR ARMIDEX-30TABS",
    composition: "",
    quantity: "",
    potency: "",
    price: 1700,
    category: "Tablets",
  },
  {
    id: 115,
    brand: "German Remedies",
    product: "GR TRENAVAR-60TABS",
    composition: "",
    quantity: "",
    potency: "",
    price: 1800,
    category: "Tablets",
  },
  {
    id: 116,
    brand: "3rd degree",
    product: "TEST PROP",
    composition: "",
    quantity: "",
    potency: "",
    price: 1000,
    category: "Injectables",
  },
  {
    id: 117,
    brand: "3rd degree",
    product: "TEST SUSPENSION",
    composition: "",
    quantity: "",
    potency: "",
    price: 1150,
    category: "Injectables",
  },
  {
    id: 118,
    brand: "3rd degree",
    product: "TEST CYPO",
    composition: "",
    quantity: "",
    potency: "",
    price: 1550,
    category: "Injectables",
  },
  {
    id: 119,
    brand: "3rd degree",
    product: "TEST ENAN",
    composition: "",
    quantity: "",
    potency: "",
    price: 1550,
    category: "Injectables",
  },
  {
    id: 120,
    brand: "3rd degree",
    product: "SUSTA 250",
    composition: "",
    quantity: "",
    potency: "",
    price: 1550,
    category: "Injectables",
  },
  {
    id: 121,
    brand: "3rd degree",
    product: "WINSTROL",
    composition: "",
    quantity: "",
    potency: "",
    price: 1375,
    category: "Injectables",
  },
  {
    id: 122,
    brand: "3rd degree",
    product: "DECA 250",
    composition: "",
    quantity: "",
    potency: "",
    price: 1825,
    category: "Injectables",
  },
  {
    id: 123,
    brand: "3rd degree",
    product: "BOLDY 250",
    composition: "",
    quantity: "",
    potency: "",
    price: 1850,
    category: "Injectables",
  },
  {
    id: 124,
    brand: "3rd degree",
    product: "MASTERON-E",
    composition: "",
    quantity: "",
    potency: "",
    price: 2375,
    category: "Injectables",
  },
  {
    id: 125,
    brand: "3rd degree",
    product: "TREN ACETATE",
    composition: "",
    quantity: "",
    potency: "",
    price: 2475,
    category: "Injectables",
  },
  {
    id: 126,
    brand: "3rd degree",
    product: "TREN ENAN",
    composition: "",
    quantity: "",
    potency: "",
    price: 2950,
    category: "Injectables",
  },
  {
    id: 127,
    brand: "3rd degree",
    product: "PRIMO",
    composition: "",
    quantity: "",
    potency: "",
    price: 2800,
    category: "Injectables",
  },
  {
    id: 128,
    brand: "3rd degree",
    product: "BULK BOMB",
    composition: "",
    quantity: "",
    potency: "",
    price: 3275,
    category: "Blends",
  },
  {
    id: 129,
    brand: "3rd degree",
    product: "KONG-700",
    composition: "",
    quantity: "",
    potency: "",
    price: 5100,
    category: "Blends",
  },
  {
    id: 130,
    brand: "3rd degree",
    product: "BLADE",
    composition: "",
    quantity: "",
    potency: "",
    price: 3950,
    category: "Blends",
  },
  {
    id: 131,
    brand: "3rd degree",
    product: "DANABOL",
    composition: "",
    quantity: "",
    potency: "",
    price: 590,
    category: "Tablets",
  },
  {
    id: 132,
    brand: "3rd degree",
    product: "ANDROLIC/OXY",
    composition: "",
    quantity: "",
    potency: "",
    price: 2200,
    category: "Tablets",
  },
  {
    id: 133,
    brand: "3rd degree",
    product: "SUPERDROL",
    composition: "",
    quantity: "",
    potency: "",
    price: 2050,
    category: "Tablets",
  },
  {
    id: 134,
    brand: "3rd degree",
    product: "ANAVAR",
    composition: "",
    quantity: "",
    potency: "",
    price: 2000,
    category: "Tablets",
  },
  {
    id: 135,
    brand: "3rd degree",
    product: "CLEN",
    composition: "",
    quantity: "",
    potency: "",
    price: 1000,
    category: "Tablets",
  },
  {
    id: 136,
    brand: "3rd degree",
    product: "T3",
    composition: "",
    quantity: "",
    potency: "",
    price: 1000,
    category: "Tablets",
  },
  {
    id: 137,
    brand: "3rd degree",
    product: "STANA TAB",
    composition: "",
    quantity: "",
    potency: "",
    price: 1100,
    category: "Tablets",
  },
  {
    id: 138,
    brand: "3rd degree",
    product: "PCT MATRIX",
    composition: "",
    quantity: "",
    potency: "",
    price: 1500,
    category: "PCT (Tablets)",
  },
  {
    id: 139,
    brand: "G Med",
    product: "BOLDE 400 (BOLDENONE)",
    composition: "",
    quantity: "10ML VIAL",
    potency: "400MG",
    price: 1600,
    category: "Injectables",
  },
  {
    id: 140,
    brand: "G Med",
    product: "BOLDE 250 (BOLDENONE)",
    composition: "",
    quantity: "10ML VIAL",
    potency: "250MG",
    price: 1400,
    category: "Injectables",
  },
  {
    id: 141,
    brand: "G Med",
    product: "ND-MIX 400 (DECA/NANDROLONE BLEND)",
    composition: "",
    quantity: "10ML VIAL",
    potency: "400MG",
    price: 1600,
    category: "Injectables",
  },
  {
    id: 142,
    brand: "G Med",
    product: "DECA 250 (DECA/NANDROLONE)",
    composition: "",
    quantity: "10ML VIAL",
    potency: "250MG",
    price: 1350,
    category: "Injectables",
  },
  {
    id: 143,
    brand: "G Med",
    product: "ALPHABOL 100 (PRIMO)",
    composition: "",
    quantity: "10ML VIAL",
    potency: "100MG",
    price: 2500,
    category: "Injectables",
  },
  {
    id: 144,
    brand: "G Med",
    product: "MASTERIL 100 (MASTERONE)",
    composition: "",
    quantity: "10ML VIAL",
    potency: "100MG",
    price: 1800,
    category: "Injectables",
  },
  {
    id: 145,
    brand: "G Med",
    product: "MASTERIL 150 (MASTERONE)",
    composition: "",
    quantity: "10ML VIAL",
    potency: "150MG",
    price: 2100,
    category: "Injectables",
  },
  {
    id: 146,
    brand: "G Med",
    product: "TEST-E 250 (TEST ENANTHATE)",
    composition: "",
    quantity: "10ML VIAL",
    potency: "250MG",
    price: 1150,
    category: "Injectables",
  },
  {
    id: 147,
    brand: "G Med",
    product: "TEST-E 350 (TEST ENANTHATE)",
    composition: "",
    quantity: "10ML VIAL",
    potency: "350MG",
    price: 1300,
    category: "Injectables",
  },
  {
    id: 148,
    brand: "G Med",
    product: "T-CYPO 250 (TEST CYPIONATE)",
    composition: "",
    quantity: "10ML VIAL",
    potency: "250MG",
    price: 1150,
    category: "Injectables",
  },
  {
    id: 149,
    brand: "G Med",
    product: "SUSTA 250 (TEST MIX)",
    composition: "",
    quantity: "10ML VIAL",
    potency: "250MG",
    price: 1200,
    category: "Injectables",
  },
  {
    id: 150,
    brand: "G Med",
    product: "ANDROPEN 400 (SUSTANON/TEST MIX)",
    composition: "",
    quantity: "10ML VIAL",
    potency: "400MG",
    price: 1400,
    category: "Injectables",
  },
  {
    id: 151,
    brand: "G Med",
    product: "T-PROP 100 (TEST PROPIONATE)",
    composition: "",
    quantity: "10ML VIAL",
    potency: "100MG",
    price: 750,
    category: "Injectables",
  },
  {
    id: 152,
    brand: "G Med",
    product: "T-PROP 150 (TEST PROPIONATE)",
    composition: "",
    quantity: "10ML VIAL",
    potency: "150MG",
    price: 900,
    category: "Injectables",
  },
  {
    id: 153,
    brand: "G Med",
    product: "TREN ACE 100 (TREN ACETATE)",
    composition: "",
    quantity: "10ML VIAL",
    potency: "100MG",
    price: 2400,
    category: "Injectables",
  },
  {
    id: 154,
    brand: "G Med",
    product: "T-HEXA 76.5 (TREN HEXA)",
    composition: "",
    quantity: "10ML VIAL",
    potency: "76.5MG",
    price: 2400,
    category: "Injectables",
  },
  {
    id: 155,
    brand: "G Med",
    product: "TREN DEPOT 200 (TREN ENANTHATE)",
    composition: "",
    quantity: "10ML VIAL",
    potency: "200MG",
    price: 2600,
    category: "Injectables",
  },
  {
    id: 156,
    brand: "G Med",
    product: "TRI TREN 200 (TREN MIX)",
    composition: "",
    quantity: "10ML VIAL",
    potency: "200MG",
    price: 2700,
    category: "Injectables",
  },
  {
    id: 157,
    brand: "G Med",
    product: "NANDRO-P 100 (NPP)",
    composition: "",
    quantity: "10ML VIAL",
    potency: "100MG",
    price: 1350,
    category: "Injectables",
  },
  {
    id: 158,
    brand: "G Med",
    product: "TEST AQ 100 (TEST SUSPENSION)",
    composition: "",
    quantity: "10ML VIAL",
    potency: "100MG",
    price: 1300,
    category: "Injectables",
  },
  {
    id: 159,
    brand: "G Med",
    product: "TREN AQ 50 (TREN SUSPENSION)",
    composition: "",
    quantity: "10ML VIAL",
    potency: "50MG",
    price: 1500,
    category: "Injectables",
  },
  {
    id: 160,
    brand: "G Med",
    product: "STANA 100 (STANOZOLOL/WINNY)",
    composition: "",
    quantity: "10ML VIAL",
    potency: "100MG",
    price: 1200,
    category: "Injectables",
  },
  {
    id: 161,
    brand: "G Med",
    product: "STANA 50 (STANOZOLOL/WINNY) - OIL BASE",
    composition: "",
    quantity: "10ML VIAL",
    potency: "50MG",
    price: 1500,
    category: "Injectables",
  },
  {
    id: 162,
    brand: "LA Anabolics",
    product: "PROPIONATE 100",
    composition: "TESTOSTERONE PROPIONATE",
    potency: "100MG/ML",
    quantity: "10ML",
    price: 1100,
    category: "Injectables",
  },
  {
    id: 162,
    brand: "LA Anabolics",
    product: "CYPIONATE 250",
    composition: "TESTOSTERONE CYPIONATE",
    potency: "250MG/ML",
    quantity: "10ML",
    price: 1705,
    category: "Injectables",
  },
  {
    id: 162,
    brand: "LA Anabolics",
    product: "TESTOVIRON 250",
    composition: "TESTOSTERONE ENANTHATE",
    potency: "250MG/ML",
    quantity: "10ML",
    price: 1705,
    category: "Injectables",
  },
  {
    id: 162,
    brand: "LA Anabolics",
    product: "TESTO SUS 100",
    composition: "TESTOSTERONE SUSPENSION",
    potency: "100MG/ML",
    quantity: "10ML",
    price: 1650,
    category: "Injectables",
  },
  {
    id: 162,
    brand: "LA Anabolics",
    product: "SUSTANON 250",
    composition: "TESTOSTERONE BLEND",
    potency: "250MG/ML",
    quantity: "10ML",
    price: 1705,
    category: "Injectables",
  },
  {
    id: 162,
    brand: "LA Anabolics",
    product: "SUSTANON 400",
    composition: "TESTOSTERONE BLEND",
    potency: "400MG/ML",
    quantity: "10ML",
    price: 2200,
    category: "Injectables",
  },
  {
    id: 162,
    brand: "LA Anabolics",
    product: "DECAMAN 250",
    composition: "NANDROLONE DECAMOATE",
    potency: "250MG/ML",
    quantity: "10ML",
    price: 2145,
    category: "Injectables",
  },
  {
    id: 162,
    brand: "LA Anabolics",
    product: "DECAMAX 350",
    composition: "NANDROLONE BLEND",
    potency: "350MG/ML",
    quantity: "10ML",
    price: 3025,
    category: "Injectables",
  },
  {
    id: 162,
    brand: "LA Anabolics",
    product: "DECAPROP 100",
    composition: "NANDROLONE PHENYL PROPIONATE",
    potency: "100MG/ML",
    quantity: "10ML",
    price: 1980,
    category: "Injectables",
  },
  {
    id: 162,
    brand: "LA Anabolics",
    product: "BOLDENONE 250",
    composition: "BOLDENONE UNDECYLENATE",
    potency: "250MG/ML",
    quantity: "10ML",
    price: 2145,
    category: "Injectables",
  },
  {
    id: 162,
    brand: "LA Anabolics",
    product: "BOLDMAX 400",
    composition: "BOLDENONE UNDECYLENATE",
    potency: "400MG/ML",
    quantity: "10ML",
    price: 3135,
    category: "Injectables",
  },
  {
    id: 162,
    brand: "LA Anabolics",
    product: "STANOZOLOL 100",
    composition: "STANOZOLOL SUSPENSION",
    potency: "100MG/ML",
    quantity: "10ML",
    price: 1815,
    category: "Injectables",
  },
  {
    id: 162,
    brand: "LA Anabolics",
    product: "PRIMOBOLAN 100",
    composition: "METHENOLONE ENANTHATE",
    potency: "100MG/ML",
    quantity: "10ML",
    price: 3410,
    category: "Injectables",
  },
  {
    id: 162,
    brand: "LA Anabolics",
    product: "MASTERONE 100",
    composition: "DROSTANOLONE PROPIONATE",
    potency: "100MG/ML",
    quantity: "10ML",
    price: 2750,
    category: "Injectables",
  },
  {
    id: 162,
    brand: "LA Anabolics",
    product: "TREN A 100",
    composition: "TRENBOLONE ACETATE",
    potency: "100MG/ML",
    quantity: "10ML",
    price: 2750,
    category: "Injectables",
  },
  {
    id: 162,
    brand: "LA Anabolics",
    product: "TREN E 200",
    composition: "TRENBOLONE ENANTHATE",
    potency: "200MG/ML",
    quantity: "10ML",
    price: 3245,
    category: "Injectables",
  },
  {
    id: 162,
    brand: "LA Anabolics",
    product: "PARABOLAN 100",
    composition: "TRENBOLONE HEXAHYDROBENZYLACARBONATE",
    potency: "100MG/ML",
    quantity: "10ML",
    price: 3300,
    category: "Injectables",
  },

  // ORALS
  {
    id: 162,
    brand: "LA Anabolics",
    product: "OXANDROLONE 10",
    composition: "OXANDROLONE",
    potency: "10MG/TAB",
    quantity: "50TABS",
    price: 2200,
    category: "Orals",
  },
  {
    id: 162,
    brand: "LA Anabolics",
    product: "CLENBUTEROLL 40",
    composition: "CLENBUTEROLL HYDROCHLORIDE",
    potency: "40MG/TAB",
    quantity: "100TABS",
    price: 990,
    category: "Orals",
  },
  {
    id: 162,
    brand: "LA Anabolics",
    product: "T3 CYTOMEL",
    composition: "LIOITHYRONINE SODIUM",
    potency: "100MG/TAB",
    quantity: "100TABS",
    price: 990,
    category: "Orals",
  },
  {
    id: 162,
    brand: "LA Anabolics",
    product: "STANOZOLOL 10",
    composition: "STANOZOLOL",
    potency: "10MG/TAB",
    quantity: "100TABS",
    price: 1155,
    category: "Orals",
  },
  {
    id: 162,
    brand: "LA Anabolics",
    product: "METHANDIENONE 10",
    composition: "METHANDIENONE",
    potency: "10MG/TAB",
    quantity: "100TABS",
    price: 660,
    category: "Orals",
  },
  {
    id: 162,
    brand: "LA Anabolics",
    product: "OXYMETHOLONE 50",
    composition: "OXYMETHOLONE",
    potency: "50MG/TAB",
    quantity: "100TABS",
    price: 2035,
    category: "Orals",
  },
  {
    id: 162,
    brand: "LA Anabolics",
    product: "MESTEROLONE 25",
    composition: "MESTEROLONE",
    potency: "25MG/TAB",
    quantity: "50TABS",
    price: 2200,
    category: "Orals",
  },
  {
    id: 163,
    brand: "Thaiger",
    product: "Test Prop - Pronorm 100",
    composition: "",
    potency: "",
    quantity: "",
    price: 925,
    category: "Injectables",
  },
  {
    id: 163,
    brand: "Thaiger",
    product: "Test Enanthate Retostyl",
    composition: "",
    potency: "",
    quantity: "",
    price: 1450,
    category: "Injectables",
  },
  {
    id: 163,
    brand: "Thaiger",
    product: "Test Cypo - Cject",
    composition: "",
    potency: "",
    quantity: "",
    price: 1450,
    category: "Injectables",
  },
  {
    id: 163,
    brand: "Thaiger",
    product: "Susta - SU 250",
    composition: "",
    potency: "",
    quantity: "",
    price: 1450,
    category: "Injectables",
  },
  {
    id: 163,
    brand: "Thaiger",
    product: "Susta - SU 400",
    composition: "",
    potency: "",
    quantity: "",
    price: 1800,
    category: "Injectables",
  },
  {
    id: 163,
    brand: "Thaiger",
    product: "Stanazolol 100 mg",
    composition: "",
    potency: "",
    quantity: "",
    price: 1700,
    category: "Injectables",
  },
  {
    id: 163,
    brand: "Thaiger",
    product: "Deca 250 mg",
    composition: "",
    potency: "",
    quantity: "",
    price: 1750,
    category: "Injectables",
  },
  {
    id: 163,
    brand: "Thaiger",
    product: "Boldy 250",
    composition: "",
    potency: "",
    quantity: "",
    price: 1750,
    category: "Injectables",
  },
  {
    id: 163,
    brand: "Thaiger",
    product: "Boldy 400",
    composition: "",
    potency: "",
    quantity: "",
    price: 2500,
    category: "Injectables",
  },
  {
    id: 163,
    brand: "Thaiger",
    product: "Tren Enanthate",
    composition: "",
    potency: "",
    quantity: "",
    price: 3000,
    category: "Injectables",
  },
  {
    id: 163,
    brand: "Thaiger",
    product: "Primo 100",
    composition: "",
    potency: "",
    quantity: "",
    price: 2800,
    category: "Injectables",
  },
  {
    id: 163,
    brand: "Thaiger",
    product: "Ripex - Cut Mix",
    composition: "",
    potency: "",
    quantity: "",
    price: 2500,
    category: "Injectables",
  },
  {
    id: 163,
    brand: "Thaiger",
    product: "Mastron (Drostanalone Prop)",
    composition: "",
    potency: "",
    quantity: "",
    price: 2150,
    category: "Injectables",
  },

  // TABLETS
  {
    id: 163,
    brand: "Thaiger",
    product: "Anavar",
    composition: "",
    potency: "",
    quantity: "",
    price: 1750,
    category: "Tablets",
  },
  {
    id: 163,
    brand: "Thaiger",
    product: "Clen",
    composition: "",
    potency: "",
    quantity: "",
    price: 875,
    category: "Tablets",
  },
  {
    id: 163,
    brand: "Thaiger",
    product: "Stana Tab",
    composition: "",
    potency: "",
    quantity: "",
    price: 1125,
    category: "Tablets",
  },
  {
    id: 163,
    brand: "Thaiger",
    product: "Oxy",
    composition: "",
    potency: "",
    quantity: "",
    price: 1550,
    category: "Tablets",
  },
  {
    id: 163,
    brand: "Thaiger",
    product: "Dainabol 100",
    composition: "",
    potency: "",
    quantity: "",
    price: 600,
    category: "Tablets",
  },
  {
    id: 163,
    brand: "Thaiger",
    product: "Dainabol 500",
    composition: "",
    potency: "",
    quantity: "",
    price: 2075,
    category: "Tablets",
  },
  {
    id: 164,
    brand: "Denik",
    product: "ANDACUDARINE",
    composition: "ANDACUDARINE (S-4)",
    potency: "10mg",
    quantity: "60 Caps",
    price: 2000,
    category: "SARMS",
  },
  {
    id: 164,
    brand: "Denik",
    product: "MUPOSTARINE",
    composition: "OSTARINE (MK-2866)",
    potency: "10mg",
    quantity: "60 Caps",
    price: 2000,
    category: "SARMS",
  },
  {
    id: 164,
    brand: "Denik",
    product: "NUTROCUBALIS",
    composition: "NUTROBAL (MK-677)",
    potency: "10mg",
    quantity: "60 Caps",
    price: 2300,
    category: "SARMS",
  },
  {
    id: 164,
    brand: "Denik",
    product: "CARDACUDARINE",
    composition: "CARDARINE (GW-501516)",
    potency: "10mg",
    quantity: "60 Caps",
    price: 2100,
    category: "SARMS",
  },
  {
    id: 164,
    brand: "Denik",
    product: "ANAMUPORIS",
    composition: "ANABOLICUM (LGD-4033)",
    potency: "10mg",
    quantity: "60 Caps",
    price: 2400,
    category: "SARMS",
  },
  {
    id: 164,
    brand: "Denik",
    product: "STENAMUPORIS",
    composition: "STENOBLIC (SR-9009)",
    potency: "10mg",
    quantity: "60 Caps",
    price: 2200,
    category: "SARMS",
  },
  {
    id: 164,
    brand: "Denik",
    product: "YUCOMUPORIS",
    composition: "YUICHIRO COMPOUND (YK-11)",
    potency: "10mg",
    quantity: "60 Caps",
    price: 2400,
    category: "SARMS",
  },
  {
    id: 164,
    brand: "Denik",
    product: "TESTOMUCORIS",
    composition: "TESTOLONE (RAD-140)",
    potency: "10mg",
    quantity: "60 Caps",
    price: 2300,
    category: "SARMS",
  },
  {
    id: 164,
    brand: "Denik",
    product: "ANABOLRONE",
    composition: "LGD-3033",
    potency: "10mg",
    quantity: "60 Caps",
    price: 2650,
    category: "SARMS",
  },
  {
    id: 164,
    brand: "Denik",
    product: "SHREDDEREX",
    composition: "MEGA SHRED MIX",
    potency: "70mg",
    quantity: "60 Caps",
    price: 5000,
    category: "SARMS",
  },
  {
    id: 164,
    brand: "Denik",
    product: "RADMAXIMA",
    composition: "TLB-150 BENZOATE (RAD-150)",
    potency: "10mg",
    quantity: "60 Caps",
    price: 2650,
    category: "SARMS",
  },
  {
    id: 164,
    brand: "Denik",
    product: "MEGADROLONE",
    composition: "MEGA BULK MIX",
    potency: "150mg",
    quantity: "60 Caps",
    price: 5500,
    category: "SARMS",
  },
  {
    id: 164,
    brand: "Denik",
    product: "OTR AC MEGA",
    composition: "OTR-AC",
    potency: "20mg",
    quantity: "60 Caps",
    price: 2250,
    category: "SARMS",
  },

  // ------------------ PEPTIDES ------------------
  {
    id: 164,
    brand: "Denik",
    product: "OTOTROPIN",
    composition: "SOMATROPIN (191 AA HGH)",
    potency: "20IU/vial",
    quantity: "5 Vials",
    price: 16000,
    category: "Peptides",
  },
  {
    id: 164,
    brand: "Denik",
    product: "FRAG-RIP",
    composition: "Tyr-hGH FRAGMENT 177-191",
    potency: "5mg/vial",
    quantity: "5 Vials",
    price: 15000,
    category: "Peptides",
  },
  {
    id: 164,
    brand: "Denik",
    product: "GROSIX-DS",
    composition: "GROWTH HORMONE RELEASING PEPTIDE-6",
    potency: "6mg/vial",
    quantity: "5 Vials",
    price: 7300,
    category: "Peptides",
  },
  {
    id: 164,
    brand: "Denik",
    product: "INSUGRO",
    composition: "RECOMBINANT IGF 1 LONG LR3",
    potency: "125mcg/vial",
    quantity: "5 Vials",
    price: 9000,
    category: "Peptides",
  },
  {
    id: 164,
    brand: "Denik",
    product: "GROWTWO",
    composition: "GROWTH HORMONE RELEASING PEPTIDE-2",
    potency: "6mg/vial",
    quantity: "5 Vials",
    price: 7500,
    category: "Peptides",
  },
  {
    id: 164,
    brand: "Denik",
    product: "INSUGRO-DS",
    composition: "RECOMBINANT IGF 1 DES",
    potency: "1mg/vial",
    quantity: "5 Vials",
    price: 9500,
    category: "Peptides",
  },
  {
    id: 164,
    brand: "Denik",
    product: "TVANIO DAC",
    composition: "CJC 1295 WITH DAC",
    potency: "2mg/vial",
    quantity: "5 Vials",
    price: 10000,
    category: "Peptides",
  },
  {
    id: 164,
    brand: "Denik",
    product: "TVANIO GRF",
    composition: "MOD GRF (CJC 1295 WITHOUT DAC)",
    potency: "2mg/vial",
    quantity: "5 Vials",
    price: 7000,
    category: "Peptides",
  },
  {
    id: 164,
    brand: "Denik",
    product: "MECHA TECH",
    composition: "MECHANO GROWTH FACTOR (IGF-1 EC)",
    potency: "2mg/vial",
    quantity: "5 Vials",
    price: 7400,
    category: "Peptides",
  },
  {
    id: 164,
    brand: "Denik",
    product: "MECHA FACTO",
    composition: "PEGYLATED MECHANO GROWTH FACTOR",
    potency: "2mg/vial",
    quantity: "5 Vials",
    price: 13000,
    category: "Peptides",
  },
  {
    id: 164,
    brand: "Denik",
    product: "FOLLITECH",
    composition: "344 AA FOLLISTATIN",
    potency: "1mg/vial",
    quantity: "5 Vials",
    price: 14500,
    category: "Peptides",
  },
  {
    id: 164,
    brand: "Denik",
    product: "HUMAGO",
    composition: "HUMAN MENOPAUSAL GONADOTROPIN",
    potency: "150IU/vial",
    quantity: "5 Vials",
    price: 8500,
    category: "Peptides",
  },
  {
    id: 164,
    brand: "Denik",
    product: "SPIERECTOR",
    composition: "PENTADECAPEPTIDE BPC-157",
    potency: "5mg/vial",
    quantity: "5 Vials",
    price: 9000,
    category: "Peptides",
  },
  {
    id: 164,
    brand: "Denik",
    product: "HEXARECT",
    composition: "GROWTH HORMONE RELEASING HEXAPEPTIDE",
    potency: "2mg/vial",
    quantity: "5 Vials",
    price: 8200,
    category: "Peptides",
  },
  {
    id: 164,
    brand: "Denik",
    product: "IPAMOTECH",
    composition: "GROWTH HORMONE RELEASING PENTAPEPTIDE",
    potency: "2mg/vial",
    quantity: "5 Vials",
    price: 8000,
    category: "Peptides",
  },
  {
    id: 164,
    brand: "Denik",
    product: "GRODIF",
    composition: "MYOSTATIN (GDF-8)",
    potency: "1mg/vial",
    quantity: "5 Vials",
    price: 14500,
    category: "Peptides",
  },
  {
    id: 164,
    brand: "Denik",
    product: "FERTIRELIN",
    composition: "TRIPORELIN (GNRH DECAPEPTYL)",
    potency: "200mcg/vial",
    quantity: "5 Vials",
    price: 1170,
    category: "Peptides",
  },
  {
    id: 164,
    brand: "Denik",
    product: "ILLUMINAGE",
    composition: "EPITALON",
    potency: "5mg/vial",
    quantity: "5 Vials",
    price: 8000,
    category: "Peptides",
  },
  {
    id: 164,
    brand: "Denik",
    product: "EXENOXY",
    composition: "EXENATIDE",
    potency: "2mg/vial",
    quantity: "5 Vials",
    price: 9000,
    category: "Peptides",
  },
  {
    id: 164,
    brand: "Denik",
    product: "HELICOTEC",
    composition: "HUMAN CHORIONIC GONADOTROPIN",
    potency: "5000IU/vial",
    quantity: "5 Vials",
    price: 2000,
    category: "Peptides",
  },
  {
    id: 164,
    brand: "Denik",
    product: "BEUCOPP",
    composition: "GHK-Cu",
    potency: "10mg/vial",
    quantity: "5 Vials",
    price: 7000,
    category: "Peptides",
  },
  {
    id: 164,
    brand: "Denik",
    product: "GLYCOTIDE",
    composition: "SEMAGLUTIDE",
    potency: "5mg/vial",
    quantity: "5 Vials",
    price: 11500,
    category: "Peptides",
  },
  {
    id: 164,
    brand: "Denik",
    product: "ERYTHROPEN",
    composition: "ERYTHROPOIETIN",
    potency: "4000IU/0.4ml",
    quantity: "1",
    price: 400,
    category: "Peptides",
  },
  {
    id: 164,
    brand: "Denik",
    product: "THYMOSY β",
    composition: "THYMOSIN β-4",
    potency: "5mg/vial",
    quantity: "5 Vials",
    price: 14000,
    category: "Peptides",
  },
  {
    id: 165,
    brand: "Superior Peptides",
    product: "HGH191AA",
    composition: "HUMAN GROWTH HORMONE 191AA",
    potency: "10IU X 1VIAL",
    quantity: "",
    price: 900,
    category: "Peptides",
  },
  {
    id: 165,
    brand: "Superior Peptides",
    product: "HGH-FRAG",
    composition: "HGH FRAGMENT 176-191",
    potency: "6MG X 1VIAL",
    quantity: "",
    price: 1000,
    category: "Peptides",
  },
  {
    id: 165,
    brand: "Superior Peptides",
    product: "GHRP-6",
    composition: "GROWTH HORMONE RELEASING PEPTIDE-6",
    potency: "5MG X 1VIAL",
    quantity: "",
    price: 800,
    category: "Peptides",
  },
  {
    id: 165,
    brand: "Superior Peptides",
    product: "IGF-1LR3",
    composition: "INSULIN-LIKE GROWTH FACTOR 1 LONG R3",
    potency: "125MCG X 1VIAL",
    quantity: "",
    price: 900,
    category: "Peptides",
  },
  {
    id: 165,
    brand: "Superior Peptides",
    product: "IPAMORELIN",
    composition: "GROWTH HORMONE RELEASING PENTA PEPTIDE",
    potency: "5MG X 1VIAL",
    quantity: "",
    price: 1100,
    category: "Peptides",
  },
  {
    id: 165,
    brand: "Superior Peptides",
    product: "GONADORELIN",
    composition: "GONADORELIN (WASHOUT CYCLE)",
    potency: "10MG X 1VIAL",
    quantity: "",
    price: 1200,
    category: "Peptides",
  },
  {
    id: 165,
    brand: "Superior Peptides",
    product: "MOD GRF (1-29)",
    composition: "CJC-1295 NON DAC",
    potency: "2MG X 1VIAL",
    quantity: "",
    price: 800,
    category: "Peptides",
  },
  {
    id: 165,
    brand: "Superior Peptides",
    product: "CJC-1295 DAC",
    composition: "CJC-1295 WITH DRUG AFFINITY COMPLEX",
    potency: "2MG X 1VIAL",
    quantity: "",
    price: 900,
    category: "Peptides",
  },
  {
    id: 165,
    brand: "Superior Peptides",
    product: "FST-344",
    composition: "FOLLISTATIN-344",
    potency: "1MG X 1VIAL",
    quantity: "",
    price: 3500,
    category: "Peptides",
  },
  {
    id: 165,
    brand: "Superior Peptides",
    product: "PT-141",
    composition: "BREMELANOTIDE",
    potency: "10MG X 1VIAL",
    quantity: "",
    price: 2500,
    category: "Peptides",
  },
  {
    id: 165,
    brand: "Superior Peptides",
    product: "BPC-157",
    composition: "BODY PROTECTION COMPOUND",
    potency: "5MG X 1VIAL",
    quantity: "",
    price: 1500,
    category: "Peptides",
  },
  {
    id: 165,
    brand: "Superior Peptides",
    product: "TB-500",
    composition: "THYMOSIN BETA-4",
    potency: "10MG X 1VIAL",
    quantity: "",
    price: 2400,
    category: "Peptides",
  },
  {
    id: 165,
    brand: "Superior Peptides",
    product: "RECOVERY BLEND",
    composition: "BPC-157 + TB-500",
    potency: "10MG X 1VIAL",
    quantity: "",
    price: 3200,
    category: "Blends",
  },
  {
    id: 165,
    brand: "Superior Peptides",
    product: "ADIPOTIDE (FTPP)",
    composition: "FAT TARGETED PROAPOPTOTIC PEPTIDE",
    potency: "10MG X 1VIAL",
    quantity: "",
    price: 2500,
    category: "Peptides",
  },
  {
    id: 165,
    brand: "Superior Peptides",
    product: "GAINING BLEND",
    composition: "GHRP-6 + MOD GRF + HEXARELIN",
    potency: "15MG X 1VIAL",
    quantity: "",
    price: 2000,
    category: "Blends",
  },
  {
    id: 165,
    brand: "Superior Peptides",
    product: "LEAN GAIN BLEND",
    composition: "GHRP-2 + CJC-1295 + IPAMORELIN",
    potency: "9MG X 1VIAL",
    quantity: "",
    price: 2400,
    category: "Blends",
  },
  {
    id: 165,
    brand: "Superior Peptides",
    product: "RIPPING BLEND",
    composition: "TESAMORELIN + CJC-1295 + IPAMORELIN",
    potency: "12MG X 1VIAL",
    quantity: "",
    price: 2000,
    category: "Blends",
  },
  {
    id: 165,
    brand: "Superior Peptides",
    product: "FAT OFF BLEND",
    composition: "HGH FRAG + CJC-1295 + IPAMORELIN",
    potency: "12MG X 1VIAL",
    quantity: "",
    price: 3000,
    category: "Blends",
  },
  {
    id: 165,
    brand: "Superior Peptides",
    product: "PGCL",
    composition: "CLOPROSTENOL SODIUM",
    potency: "2MG X 1VIAL",
    quantity: "",
    price: 550,
    category: "Peptides",
  },
  {
    id: 165,
    brand: "Superior Peptides",
    product: "AOD",
    composition: "ANTI OBESITY DRUG",
    potency: "2MG X 1VIAL",
    quantity: "",
    price: 1300,
    category: "Peptides",
  },
  {
    id: 165,
    brand: "Superior Peptides",
    product: "SEMAGLUTIDE",
    composition: "SEMAGLUTIDE (GLP-1 ANALOGUE)",
    potency: "2MG X 1VIAL",
    quantity: "",
    price: 3500,
    category: "Peptides",
  },
  {
    id: 165,
    brand: "Superior Peptides",
    product: "GROWTH FACTOR MIX",
    composition: "IGF-1LR3 + MGF",
    potency: "2125MCG X 1VIAL",
    quantity: "",
    price: 1500,
    category: "Blends",
  },
  {
    id: 165,
    brand: "Superior Peptides",
    product: "IGF-1 DES",
    composition: "RECOMBINANT IGF-1 DES",
    potency: "1MG X 1VIAL",
    quantity: "",
    price: 1000,
    category: "Peptides",
  },
  {
    id: 165,
    brand: "Superior Peptides",
    product: "BACTERIOSTATIC WATER",
    composition: "BACTERIOSTATIC WATER",
    potency: "10ML X 1VIAL",
    quantity: "",
    price: 400,
    category: "Accessories",
  },
];
